services:
  letterboxle-backend:
    container_name: letterboxle-backend
    build: .
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    environment:
      - DB_URL=${DB_URL}
      - PLATFORM=${PLATFORM}
      - PORT=${PORT}
      - TMDB_API_KEY=${TMDB_API_KEY}
    networks:
      - npm

networks:
  npm:
    external: true